### ISSUE TITLE
Calibration error for regression models.

### ISSUE THREAD

**Issue by DwaraknathT** [devmotion/CalibrationErrors.jl#116]
Hi, 

Thank you for work you've done on the project! I was wondering if you could provide some examples on how to use this package for regression models please? There were a couple of lines in the documentation that we must use a more general distance metric but I am not sure how exactly to do it.

**Comment by devmotion** [comment]
Hi!

You can find some examples in our ICLR paper and the accompanying repo: https://github.com/devmotion/Calibration_ICLR2021 E.g., one example you can find here: https://devmotion.github.io/Calibration_ICLR2021/dev/generated/friedman/ The examples use https://github.com/devmotion/CalibrationErrorsDistributions.jl which contains support for different combinations of kernels and predicted distributions.

My plan was to add a, possibly separate, documentation for this package and show some regression problems, and I also wanted to refactor the calibration packages a bit, add Monte Carlo estimators as fallback, and add goodies from my local branch such as optimization of kernel (parameters)... Unfortunately, probably it will take a while since I am on parental leave currently and can't spend much time on it.

**Comment by DwaraknathT** [comment]
Thank you very much for your reply! will definitely go through the pointed directions.
